[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/sms/send"
  to = "/.netlify/functions/sms"
  status = 200
  force = true

[[redirects]]
  from = "/favicon.ico"
  to = "/maktabx-logo.png"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
